export const colors = {
    magenta: "magenta",
    gray: "#AAA",
    darkGray: "#444",
    deepMainColor: "#66A1FF",
    lightMainColor: "#B8D4FF",
    blurredGray: "#E5E5E5",
    buttonBlue: "#007AFF",
    white: "#fff",
    black: "#000",
    gray1: "#333",
    gray2: "#666",
    gray3: "#999",
    gray4: "#ccc",
};
