export const colors = {
    magenta: "magenta",
    background: "#EFEFEF",
    surveyBoxBackground: "#fff",
    gray: "#AAA",
    darkGray: "#444",
    deepMainColor: "#66A1FF",
    lightMainColor: "#B8D4FF",
    blurredGray: "#E5E5E5",
    buttonBlue: "#007AFF",
    inactiveBtnBG: "#C9C9C9",
    white: "#fff",
    black: "#000",
    gray1: "#333",
    gray2: "#666",
    gray3: "#999",
    gray4: "#ccc",
    gray5: "#fff",
    transparent: "rgba(0,0,0,0)",
    modalBackground: "rgba(0, 0, 0, 0.75)",
    unselectedQuestionBoxBG: "#DCEAFF",
    selectedQuestionBoxBG: "#5094FD",
    unselectedQuestionBoxText: "#777777",
    placeHolder: "#C5C5C5",
};
